workspace(name = "MyTest")
# TensorFlow external dependencies that can be loaded in WORKSPACE files.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//MyTest:workspace.bzl", "tf_http_archive")
load("//MyTest:workspace.bzl", "clean_dep")


# Google Test
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/release-1.10.0.zip"],
  strip_prefix = "googletest-release-1.10.0",
  sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
)

tf_http_archive(
    name = "pthreadpool",
    sha256 = "e576de3e2504018462a3ee2282c99c2d0d708f01d17cd2f71f9f1fe6d3ba8b9b",
    strip_prefix = "pthreadpool-77f9d3bcfabd1bdb910dd33b549d5290b968ef05",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/pthreadpool/archive/77f9d3bcfabd1bdb910dd33b549d5290b968ef05.zip",
        "https://github.com/Maratyszcza/pthreadpool/archive/77f9d3bcfabd1bdb910dd33b549d5290b968ef05.zip",
    ],
)

tf_http_archive(
    name = "com_google_googletest",
    sha256 = "ff7a82736e158c077e76188232eac77913a15dac0b22508c390ab3f88e6d6d86",
    strip_prefix = "googletest-b6cd405286ed8635ece71c72f118e659f4ade3fb",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/googletest/archive/b6cd405286ed8635ece71c72f118e659f4ade3fb.zip",
        "https://github.com/google/googletest/archive/b6cd405286ed8635ece71c72f118e659f4ade3fb.zip",
    ],
)

LLVM_COMMIT = "f89f6d1e5d7d9cefd9e1d4c7a17afb53245a1fa8"
LLVM_SHA256 = "dcc663ea8f53345c709ad36bd71fc67102bac7590357dc7a46260074317759cc"
LLVM_URLS = [
    "https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
    "https://github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
]
tf_http_archive(
    name = "llvm-project",
    sha256 = LLVM_SHA256,
    strip_prefix = "llvm-project-" + LLVM_COMMIT,
    urls = LLVM_URLS,
    additional_build_files = {
        clean_dep("//third_party/llvm:llvm.autogenerated.BUILD"): "llvm/BUILD",
        "//third_party/mlir:BUILD": "mlir/BUILD",
        "//third_party/mlir:test.BUILD": "mlir/test/BUILD",
    },
)



# Intel openMP that is part of LLVM sources.
tf_http_archive(
    name = "llvm_openmp",
    build_file = clean_dep("//third_party/llvm_openmp:BUILD"),
    sha256 = "d19f728c8e04fb1e94566c8d76aef50ec926cd2f95ef3bf1e0a5de4909b28b44",
    strip_prefix = "openmp-10.0.1.src",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz",
        "https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz",
    ],
)
